/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package canteenreservation;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Steve
 */
public class LoadingScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoadingScreen
     */
    public LoadingScreen() {
        initComponents();
    }
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bar = new javax.swing.JProgressBar();
        drinksLabel2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        progress = new javax.swing.JLabel();
        drinksLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bar.setBackground(new java.awt.Color(51, 0, 0));
        bar.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 380, 10));

        drinksLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 40)); // NOI18N
        drinksLabel2.setForeground(new java.awt.Color(51, 0, 0));
        drinksLabel2.setText("eat . live . love");
        jPanel1.add(drinksLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ClientIcons/loading screen.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        progress.setFont(new java.awt.Font("Artifakt Element", 1, 14)); // NOI18N
        progress.setForeground(new java.awt.Color(0, 0, 0));
        progress.setText("0%");
        jPanel1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 37, -1));

        drinksLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 60)); // NOI18N
        drinksLabel3.setForeground(new java.awt.Color(204, 0, 51));
        drinksLabel3.setText("welcome");
        jPanel1.add(drinksLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        LoadingScreen sc = new LoadingScreen();
        Login log = new Login();
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                sc.setVisible(true);
            }
        });
         try{
            for(int i=0;i<=100;i++){
             Thread.sleep(40);
            sc.bar.setValue(i);
            sc.progress.setText(Integer.toString(i)+ "%");
            
            }
        }catch(Exception e){
            
        }
        sc.dispose();
        log.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel drinksLabel2;
    private javax.swing.JLabel drinksLabel3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel progress;
    // End of variables declaration//GEN-END:variables
}
